services:
  speedtest-display:
    build:
      context: ./display
      dockerfile: ./Dockerfile
    image: therenoth234/speedtest-display:latest
    container_name: speedtest-display
    ports:
      - "8080:8080"
    volumes:
      - /mnt/g/developement/speedtest/log:/app/log
    depends_on:
      - speedtest-backend
    restart: on-failure:0

  speedtest-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: therenoth234/speedtest-backend:latest
    container_name: speedtest-backend
    env_file: ./.env
    network_mode: "host"
    volumes:
      - /mnt/g/developement/speedtest/log:/app/log
      - /mnt/g/developement/speedtest/binaries/ookla:/usr/local/bin:ro
    restart: on-failure:0
